# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0



source "https://rubygems.org"

gem "net-smtp", "~> 0.5.2"
gem "pony",     "~> 1.13"
gem "puma",     "~> 8.0"
gem "sinatra",  "~> 4.2"
gem "rackup",   "~> 2.3"

gem "google-protobuf", "~> 4.36.2"

gem "ostruct"

gem "opentelemetry-sdk",                   "~> 1.13"
gem "opentelemetry-common",                "~> 0.25"
gem "opentelemetry-logs-sdk",              "~> 0.7"
gem 'opentelemetry-metrics-sdk',           "~> 0.19"
gem "opentelemetry-exporter-otlp",         "~> 0.37"
gem 'opentelemetry-exporter-otlp-metrics', "~> 0.13"
gem 'opentelemetry-exporter-otlp-logs',    "~> 0.6"
gem "opentelemetry-instrumentation-all",   "~> 0.97"

gem "openfeature-sdk", "~> 0.6"
gem "openfeature-flagd-provider", "~> 0.1"
