opentelemetry-collector:
  config:
    exporters:
      otlp/grafana-alloy:
        endpoint: grafana-k8s-monitoring-alloy-receiver:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            - kafkametrics
            - spanmetrics
            - receiver_creator/metrics
            - hostmetrics
            - kubeletstats
            - k8s_cluster
          processors:
            - k8sattributes
            - memory_limiter
            - resourcedetection
            - resource
            - batch
          exporters:
            - otlphttp/prometheus
            - debug
            - otlp/grafana-alloy
        traces:
          receivers:
            - otlp
            - jaeger
            - zipkin
          processors:
            - k8sattributes
            - memory_limiter
            - resourcedetection
            - resource
            - transform
            - batch
          exporters:
            - otlp/jaeger
            - debug
            - spanmetrics
            - otlp/grafana-alloy
